TYPE=VIEW
query=select `cqrlog001`.`cqrlog_main`.`id_cqrlog_main` AS `id_cqrlog_main`,`cqrlog001`.`cqrlog_main`.`qsodate` AS `qsodate`,`cqrlog001`.`cqrlog_main`.`time_on` AS `time_on`,`cqrlog001`.`cqrlog_main`.`time_off` AS `time_off`,`cqrlog001`.`cqrlog_main`.`callsign` AS `callsign`,`cqrlog001`.`cqrlog_main`.`freq` AS `freq`,`cqrlog001`.`cqrlog_main`.`mode` AS `mode`,`cqrlog001`.`cqrlog_main`.`rst_s` AS `rst_s`,`cqrlog001`.`cqrlog_main`.`rst_r` AS `rst_r`,`cqrlog001`.`cqrlog_main`.`name` AS `name`,`cqrlog001`.`cqrlog_main`.`qth` AS `qth`,`cqrlog001`.`cqrlog_main`.`qsl_s` AS `qsl_s`,`cqrlog001`.`cqrlog_main`.`qsl_r` AS `qsl_r`,`cqrlog001`.`cqrlog_main`.`qsl_via` AS `qsl_via`,`cqrlog001`.`cqrlog_main`.`iota` AS `iota`,`cqrlog001`.`cqrlog_main`.`pwr` AS `pwr`,`cqrlog001`.`cqrlog_main`.`itu` AS `itu`,`cqrlog001`.`cqrlog_main`.`waz` AS `waz`,`cqrlog001`.`cqrlog_main`.`loc` AS `loc`,`cqrlog001`.`cqrlog_main`.`my_loc` AS `my_loc`,`cqrlog001`.`cqrlog_main`.`county` AS `county`,`cqrlog001`.`cqrlog_main`.`award` AS `award`,`cqrlog001`.`cqrlog_main`.`remarks` AS `remarks`,`cqrlog001`.`cqrlog_main`.`band` AS `band`,`cqrlog001`.`dxcc_id`.`dxcc_ref` AS `dxcc_ref`,`cqrlog001`.`cqrlog_main`.`qso_dxcc` AS `qso_dxcc`,`cqrlog001`.`cqrlog_main`.`profile` AS `profile`,`cqrlog001`.`cqrlog_main`.`idcall` AS `idcall`,`cqrlog001`.`cqrlog_main`.`state` AS `state`,`cqrlog001`.`cqrlog_main`.`lotw_qslsdate` AS `lotw_qslsdate`,`cqrlog001`.`cqrlog_main`.`lotw_qslrdate` AS `lotw_qslrdate`,`cqrlog001`.`cqrlog_main`.`lotw_qsls` AS `lotw_qsls`,`cqrlog001`.`cqrlog_main`.`lotw_qslr` AS `lotw_qslr`,`cqrlog001`.`cqrlog_main`.`cont` AS `cont`,`cqrlog001`.`cqrlog_main`.`qsls_date` AS `qsls_date`,`cqrlog001`.`cqrlog_main`.`qslr_date` AS `qslr_date`,`cqrlog001`.`cqrlog_main`.`club_nr1` AS `club_nr1`,`cqrlog001`.`cqrlog_main`.`club_nr2` AS `club_nr2`,`cqrlog001`.`cqrlog_main`.`club_nr3` AS `club_nr3`,`cqrlog001`.`cqrlog_main`.`club_nr4` AS `club_nr4`,`cqrlog001`.`cqrlog_main`.`club_nr5` AS `club_nr5`,`cqrlog001`.`cqrlog_main`.`eqsl_qsl_sent` AS `eqsl_qsl_sent`,`cqrlog001`.`cqrlog_main`.`eqsl_qslsdate` AS `eqsl_qslsdate`,`cqrlog001`.`cqrlog_main`.`eqsl_qsl_rcvd` AS `eqsl_qsl_rcvd`,`cqrlog001`.`cqrlog_main`.`eqsl_qslrdate` AS `eqsl_qslrdate`,concat(`cqrlog001`.`cqrlog_main`.`qsl_r`,`cqrlog001`.`cqrlog_main`.`lotw_qslr`,`cqrlog001`.`cqrlog_main`.`eqsl_qsl_rcvd`) AS `qslr`,`cqrlog001`.`dxcc_id`.`country` AS `country` from (`cqrlog001`.`cqrlog_main` join `cqrlog001`.`dxcc_id` on((`cqrlog001`.`dxcc_id`.`adif` = `cqrlog001`.`cqrlog_main`.`adif`))) order by `cqrlog001`.`cqrlog_main`.`callsign`
md5=b205e01e4c2cb00367d2519fa4cdf84c
updatable=1
algorithm=0
definer_user=
definer_host=
suid=2
with_check_option=0
timestamp=2018-03-03 21:32:44
create-version=2
source=SELECT id_cqrlog_main,qsodate,time_on,time_off,callsign, freq,mode,rst_s,rst_r,name,qth,qsl_s,qsl_r,qsl_via,iota,pwr,itu,waz,loc,my_loc,county,\naward,remarks, band, dxcc_id.dxcc_ref AS dxcc_ref ,qso_dxcc, profile,idcall, state, lotw_qslsdate, lotw_qslrdate,lotw_qsls, lotw_qslr, cont, qsls_date,qslr_date,club_nr1,club_nr2,club_nr3,\nclub_nr4,club_nr5,eqsl_qsl_sent,eqsl_qslsdate,eqsl_qsl_rcvd,eqsl_qslrdate,concat(qsl_r,lotw_qslr,eqsl_qsl_rcvd) as qslr,dxcc_id.country FROM cqrlog_main JOIN dxcc_id ON dxcc_id.adif = cqrlog_main.adif order by callsign
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `cqrlog001`.`cqrlog_main`.`id_cqrlog_main` AS `id_cqrlog_main`,`cqrlog001`.`cqrlog_main`.`qsodate` AS `qsodate`,`cqrlog001`.`cqrlog_main`.`time_on` AS `time_on`,`cqrlog001`.`cqrlog_main`.`time_off` AS `time_off`,`cqrlog001`.`cqrlog_main`.`callsign` AS `callsign`,`cqrlog001`.`cqrlog_main`.`freq` AS `freq`,`cqrlog001`.`cqrlog_main`.`mode` AS `mode`,`cqrlog001`.`cqrlog_main`.`rst_s` AS `rst_s`,`cqrlog001`.`cqrlog_main`.`rst_r` AS `rst_r`,`cqrlog001`.`cqrlog_main`.`name` AS `name`,`cqrlog001`.`cqrlog_main`.`qth` AS `qth`,`cqrlog001`.`cqrlog_main`.`qsl_s` AS `qsl_s`,`cqrlog001`.`cqrlog_main`.`qsl_r` AS `qsl_r`,`cqrlog001`.`cqrlog_main`.`qsl_via` AS `qsl_via`,`cqrlog001`.`cqrlog_main`.`iota` AS `iota`,`cqrlog001`.`cqrlog_main`.`pwr` AS `pwr`,`cqrlog001`.`cqrlog_main`.`itu` AS `itu`,`cqrlog001`.`cqrlog_main`.`waz` AS `waz`,`cqrlog001`.`cqrlog_main`.`loc` AS `loc`,`cqrlog001`.`cqrlog_main`.`my_loc` AS `my_loc`,`cqrlog001`.`cqrlog_main`.`county` AS `county`,`cqrlog001`.`cqrlog_main`.`award` AS `award`,`cqrlog001`.`cqrlog_main`.`remarks` AS `remarks`,`cqrlog001`.`cqrlog_main`.`band` AS `band`,`cqrlog001`.`dxcc_id`.`dxcc_ref` AS `dxcc_ref`,`cqrlog001`.`cqrlog_main`.`qso_dxcc` AS `qso_dxcc`,`cqrlog001`.`cqrlog_main`.`profile` AS `profile`,`cqrlog001`.`cqrlog_main`.`idcall` AS `idcall`,`cqrlog001`.`cqrlog_main`.`state` AS `state`,`cqrlog001`.`cqrlog_main`.`lotw_qslsdate` AS `lotw_qslsdate`,`cqrlog001`.`cqrlog_main`.`lotw_qslrdate` AS `lotw_qslrdate`,`cqrlog001`.`cqrlog_main`.`lotw_qsls` AS `lotw_qsls`,`cqrlog001`.`cqrlog_main`.`lotw_qslr` AS `lotw_qslr`,`cqrlog001`.`cqrlog_main`.`cont` AS `cont`,`cqrlog001`.`cqrlog_main`.`qsls_date` AS `qsls_date`,`cqrlog001`.`cqrlog_main`.`qslr_date` AS `qslr_date`,`cqrlog001`.`cqrlog_main`.`club_nr1` AS `club_nr1`,`cqrlog001`.`cqrlog_main`.`club_nr2` AS `club_nr2`,`cqrlog001`.`cqrlog_main`.`club_nr3` AS `club_nr3`,`cqrlog001`.`cqrlog_main`.`club_nr4` AS `club_nr4`,`cqrlog001`.`cqrlog_main`.`club_nr5` AS `club_nr5`,`cqrlog001`.`cqrlog_main`.`eqsl_qsl_sent` AS `eqsl_qsl_sent`,`cqrlog001`.`cqrlog_main`.`eqsl_qslsdate` AS `eqsl_qslsdate`,`cqrlog001`.`cqrlog_main`.`eqsl_qsl_rcvd` AS `eqsl_qsl_rcvd`,`cqrlog001`.`cqrlog_main`.`eqsl_qslrdate` AS `eqsl_qslrdate`,concat(`cqrlog001`.`cqrlog_main`.`qsl_r`,`cqrlog001`.`cqrlog_main`.`lotw_qslr`,`cqrlog001`.`cqrlog_main`.`eqsl_qsl_rcvd`) AS `qslr`,`cqrlog001`.`dxcc_id`.`country` AS `country` from (`cqrlog001`.`cqrlog_main` join `cqrlog001`.`dxcc_id` on((`cqrlog001`.`dxcc_id`.`adif` = `cqrlog001`.`cqrlog_main`.`adif`))) order by `cqrlog001`.`cqrlog_main`.`callsign`
mariadb-version=100131
